project:
  type: website

website:
  title: "My Project Site"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notebook"
        href: notebook.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
